---
sudo: required
language: python
services:
  - docker
install:
  - python3 -m pip install molecule molecule-docker
  # - python3 -m pip install required driver (e.g. docker, shade, boto, apache-libcloud)
script:
  - molecule test