---
# handlers file for xray
- name: restart xray
  become: true
  systemd:
    name: "{{ xray_daemon }}"
    state: restarted

- name: stop xray
  become: true
  systemd:
    name: "{{ xray_daemon }}"
    state: stopped
