---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Collect facts about system services
      service_facts:
      register: services_state

    - name: Example assertion
      ansible.builtin.assert:
        that: services_state["ansible_facts"]["services"]["artifactory.service"]["state"] is "running"
