---
# handlers file for distribution
- name: restart artifactory
  become: true
  systemd:
    name: "{{ artifactory_daemon }}"
    state: restarted

- name: stop artifactory
  become: true
  systemd:
    name: "{{ artifactory_daemon }}"
    state: stopped
